FROM ubuntu
# Set timezone:
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

# Install dependencies:
RUN apt-get update && apt-get install -y tzdata

ENV TZ=Europe/Kiev
RUN apt-get update
RUN apt-get install -y  apache2
RUN apt-get clean
ADD  index.html /var/www/html/
ENTRYPOINT apache2ctl -D FOREGROUND